### ISSUE TITLE
Make the hashtag or Username clickable

### ISSUE THREAD

**Issue by futurbotconsolidated** [alessiaAmitrano/hashtag-mention-colorizer#19]
We have successfully coloured the hashtags and @'s, But What if we have to implement the click functionality on the same.

**Comment by alessiaAmitrano** [comment]
Hi there, I would probably suggest you to use the `(click)` attribute on the element or on a wrapper. Es:

```
<span [innerHTML]="hashtag | hmColor" (click)="share()"></span>
```
or
```
  <div (click)="share()">
    <span [innerHTML]="hashtag | hmColor"></span>
  </div>
```

**Comment by futurbotconsolidated** [comment]
Thank you for the early reply @alessiaAmitrano. 
I will tell you the problem with the help of an example.

For Ex: I am displaying the following text.
"Hi, I am abhey sharma. Who are you? #question @alessiaAmitrano "

Now this library is coloring the hashtah and @'s but What I am trying to say is that. I want the hashtags and @'s to be clickable to.
Hashtags if clicked should redirect the user to particular URL .... example.com/tags=question
@ should take the user to particular URL ... example.com/alessiaAmitrano

I hope I am clear this time.

**Comment by alessiaAmitrano** [comment]
@futurbotconsolidated  I am afraid that is not a feature provided by the library. This library is focused on the styling of a string, not on creating a real hashtag or mention. If you are looking for that, then you willl have to wrap the string in an anchor tag with the right url.
